# Configuração temporária para teste de gráficos
saida:
  pasta: "./analises_comparacao_summa_teste"
  arquivo_base: "comparacao_summa"
  regerar_planilha_base: false # FALSE para usar o excel existente

execucao:
  max_workers: 10
  teste_rapido: false
  gerar_graficos: true
  llm_as_a_judge: false
  analise_estatistica: false
  ignorar_erro_extracao: false

modelo_base:
  pasta: "./saidas/ext_gpt5r_11"
  rotulo: "gpt5r_11"
  familia: "GPT-5"

modelos_comparacao:
  - pasta: "./saidas/ext_qwen-7b_11"
    rotulo: "qwen-7b_11"
    familia: "Qwen-7B"
  
  - pasta: "./saidas/ext_jurema-7b_11"
    rotulo: "jurema-7b_11"
    familia: "Jurema-7B"
    ativo: false

  - pasta: "./saidas/ext_qwen235b_11"
    rotulo: "qwen235b_11"
    familia: "Qwen-235B"

configuracao_comparacao:
  nivel_campos: 1
  padronizar_simbolos: true
  rouge_stemmer: true
  nome_campo_id: "id"
  rotulo_campo_id: "ID"
  mascaras:
    extracao: "^(.+)\\.txt$"
    tokens: ".json" 
    avaliacao: ".avaliacao.json"
    observabilidade: ".obs.json"

  campos:
    bertscore:
      - "(global)"
      - "Materia"
      - "Resumo"
      - "Dispositivo"
    rouge_l:
    rouge_2:
      - "(global)"
      - "Materia"
      - "Resumo"
    levenshtein:
      - "Tipo"
      - "DataJulgamento"
